name: versions auto-update
# This workflow is triggered once a day
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    # Job name is Greeting
    name: versions auto-update
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: autoupdate-script
      shell: bash
      run: |
        sh versions-auto.sh
      #env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: create-mr
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pull-request -m "Auto update versions"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


